### ISSUE TITLE
outsiders guide suggestion

### ISSUE THREAD

**Issue by TamaMcGlinn** [pyjarrett/programming-with-ada#9]
On slide 13 of [these slides](https://fosdem.org/2022/schedule/event/ada_outsiders_guide/attachments/slides/5027/export/events/attachments/ada_outsiders_guide/slides/5027/Outsiders_Guide_To_Ada.pdf), perhaps have the function end with ```**return ** something```. I'm looking forward to Sunday. Cheers.

**Comment by pyjarrett** [comment]
I appreciate the suggestion, but the slide will make more sense with the video.

The presentation isn't designed to teach Ada or try to convince people to use it or not to use it, it's a high-level view of the language to help people understand it better.

I intermix regular code with pseudocode here on purpose, to show the language is often internally consistent, and an extraneous detail they'd expect from the term `function` here, along with the "return Value" above it distinguishing it from `void`, would dilute my message here.

The intent is to show how the various structures are similar - all 6 providing declarative blocks, 5 providing executable blocks, and 2 providing explicit encapsulation.  Learning three simple structures `is` (declare things), `begin` (do steps), and `private` elements for encapsulation, thereby cover all of the structural elements.  These three concepts of "declare", "do", and "hide" get split up in many different and often dissimilar ways in other languages, which is the difference I'm trying to lead the listener to understand.

There's a few conceptual lines I draw to help non-Ada programmers, which aren't as straightforward as show, but should ease understanding falling into its correct place when they do know more about the full details (like task types and protected types are actually types--it says so in their names!).  These sorts of things throughout the presentation might irritate seasoned Ada programmers since they look like mistakes (either due to omission or over-simplification), but make it easier for those unfamiliar with the language.
